---


- name: Fail if no administrative email set
  fail:
    msg: "You must set the admin_email variable."
  when: not admin_email

- include: "{{ ansible_os_family }}.yml"

- name: "Generate new certificates as necessary"
  shell: >
    certbot certonly --nginx --email '{{ admin_email }}'
    --agree-tos -d '{{ item }}'
    {% if certbot_staging %} --staging {% endif %}
  args:
    creates: "/etc/letsencrypt/live/{{ item }}/cert.pem"
  loop: "{{ certbot_hosts }}"

- name: "Test renewal with a dry run."
  shell: >
    certbot renew --dry-run --nginx

- name: Cron job to auto renew certificates via certbot
  when: certbot_renew_at|bool
  cron:
    name="Automatically renew Let's Encrypt certificates via certbot"
    job="certbot renew --quiet --no-self-upgrade --nginx"
    user=root
    minute={{ item.minute }}
    hour={{ item.hour }}
  with_items: "{{ [certbot_renew_at] }}"
